config:
  #Mongo
  mongodb:
    hostname: localhost
    port: 27017
    database: controledelogistica

  #RabbitMQ message
  amq:
    hostname: localhost
    port: 5672
    username: guest
    password: guest

  encomenda:
    exchange: encomenda.exchange
    sendDLQQueue: encomenda.sendDLQQueue
    sendQueue: encomenda.sendQueue

  atualizarFrete:
    exchange: atualizarFrete.exchange
    sendDLQQueue: atualizarFrete.sendDLQQueue
    sendQueue: atualizarFrete.sendQueue

  atualizarVeiculo:
    exchange: atualizarVeiculo.exchange
    sendDLQQueue: atualizarVeiculo.sendDLQQueue
    sendQueue: atualizarVeiculo.sendQueue

  atualizarLogistica:
    exchange: atualizarLogistica.exchange
    sendDLQQueue: atualizarLogistica.sendDLQQueue
    sendQueue: atualizarLogistica.sendQueue

  atualizarExpedicao:
    exchange: atualizarExpedicao.exchange
    sendDLQQueue: atualizarExpedicao.sendDLQQueue
    sendQueue: atualizarExpedicao.sendQueue


#Servidor Web
server:
  port: 8082


