version: "3.4"
services:

#RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - "16672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - network_pedido

#Mongo DB
  mongodb:
    image: mongo
    networks:
      - network_pedido

#Config Server
  configserver:
    build: 
      context: configServer
      dockerfile: src/main/docker/Dockerfile
      args:
        JAR_FILE: target/app.jar
        UTIL_DIR: src/main/docker/
    ports:
      - "9888:8888"
    environment:
      - JAVA_OPTS=-Xmx256m -Xms128m -Dspring.profiles.active=docker-compose
    networks:
      - network_pedido

  #Eureka Server
#  eurekaserver:
#      build:
#        context: eurekaServer
#        dockerfile: src/main/docker/Dockerfile
#        args:
#          JAR_FILE: target/app.jar
#          UTIL_DIR: src/main/docker/
#      ports:
#        - "9761:8761"
#      environment:
#        - JAVA_OPTS=-Xmx256m -Xms128m -Dspring.profiles.active=docker-compose
#      networks:
#        - network_pedido

  #Coleta
  coleta:
    build: 
      context: coleta
      dockerfile: src/main/docker/Dockerfile
      args:
        JAR_FILE: target/app.jar
        UTIL_DIR: src/main/docker/
    ports:
      - "9081:8081"
    environment:
      - WAIT_FOR_IT=rabbitmq:5672 configserver:9888
      - JAVA_OPTS=-Xmx256m -Xms128m -Dspring.profiles.active=docker-compose
      - URI_CONFIG_SERVER=http://configserver:9888 
      - URI_EUREKA_SERVER=http://eurekaserver:9761
    networks:
      - network_pedido  
#
#  controledefrete:
#    build:
#      context: controledefrete
#      dockerfile: src/main/docker/Dockerfile
#      args:
#        JAR_FILE: target/app.jar
#        UTIL_DIR: src/main/docker/
#    ports:
#      - "9082:8082"
#    environment:
#      - WAIT_FOR_IT=rabbitmq:5672 configserver:9888
#      - JAVA_OPTS=-Xmx256m -Xms128m -Dspring.profiles.active=docker-compose
#      # - URI_EUREKA_SERVER=http://eurekaserver:9761
#      - URI_CONFIG_SERVER=http://configserver:9888
#    networks:
#      - network_pedido
#
#  controledefaturamento:
#    build:
#      context: controledefaturamento
#      dockerfile: src/main/docker/Dockerfile
#      args:
#        JAR_FILE: target/app.jar
#        UTIL_DIR: src/main/docker/
#    ports:
#      - "9083:8083"
#    environment:
#      - WAIT_FOR_IT=rabbitmq:5672 configserver:9888
#      - JAVA_OPTS=-Xmx256m -Xms128m -Dspring.profiles.active=docker-compose
#      # - URI_EUREKA_SERVER=http://eurekaserver:9761
#      - URI_CONFIG_SERVER=http://configserver:9888
#    networks:
#      - network_pedido
#
#  controledefrota:
#    build:
#      context: controledefrota
#      dockerfile: src/main/docker/Dockerfile
#      args:
#        JAR_FILE: target/app.jar
#        UTIL_DIR: src/main/docker/
#    ports:
#      - "9084:8084"
#    environment:
#      - WAIT_FOR_IT=rabbitmq:5672 configserver:9888
#      - JAVA_OPTS=-Xmx256m -Xms128m -Dspring.profiles.active=docker-compose
#      # - URI_EUREKA_SERVER=http://eurekaserver:9761
#      - URI_CONFIG_SERVER=http://configserver:9888
#    networks:
#      - network_pedido
#
#  controledelogistica:
#    build:
#      context: controledelogistica
#      dockerfile: src/main/docker/Dockerfile
#      args:
#        JAR_FILE: target/app.jar
#        UTIL_DIR: src/main/docker/
#    ports:
#      - "9085:8085"
#    environment:
#      - WAIT_FOR_IT=rabbitmq:5672 configserver:9888
#      - JAVA_OPTS=-Xmx256m -Xms128m -Dspring.profiles.active=docker-compose
#      # - URI_EUREKA_SERVER=http://eurekaserver:9761
#      - URI_CONFIG_SERVER=http://configserver:9888
#    networks:
#      - network_pedido
#
#  controledeexpedicao:
#    build:
#      context: controledeexpedicao
#      dockerfile: src/main/docker/Dockerfile
#      args:
#        JAR_FILE: target/app.jar
#        UTIL_DIR: src/main/docker/
#    ports:
#      - "9086:8086"
#    environment:
#      - WAIT_FOR_IT=rabbitmq:5672 configserver:9888
#      - JAVA_OPTS=-Xmx256m -Xms128m -Dspring.profiles.active=docker-compose
#      # - URI_EUREKA_SERVER=http://eurekaserver:9761
#      - URI_CONFIG_SERVER=http://configserver:9888
#    networks:
#      - network_pedido
#
#  controledesac:
#    build:
#      context: controledesac
#      dockerfile: src/main/docker/Dockerfile
#      args:
#        JAR_FILE: target/app.jar
#        UTIL_DIR: src/main/docker/
#    ports:
#      - "9087:8087"
#    environment:
#      - WAIT_FOR_IT=rabbitmq:5672 configserver:9888
#      - JAVA_OPTS=-Xmx256m -Xms128m -Dspring.profiles.active=docker-compose
#      # - URI_EUREKA_SERVER=http://eurekaserver:9761
#      - URI_CONFIG_SERVER=http://configserver:9888
#    networks:
#      - network_pedido

  integrador:
    build: 
      context: integrador
      dockerfile: src/main/docker/Dockerfile
      args:
        JAR_FILE: target/app.jar
        UTIL_DIR: src/main/docker/
    ports:
      - "9000:7000"
    environment:
      - WAIT_FOR_IT= configserver:9888
      - JAVA_OPTS=-Xmx256m -Xms128m -Dspring.profiles.active=docker-compose
      # - URI_EUREKA_SERVER=http://eurekaserver:9761
      - URI_CONFIG_SERVER=http://configserver:9888 
    networks:
      - network_pedido  


networks:
    network_pedido: