server:
  port: 8081

freteExterno:
  ribbon:
    listOfServers: http://localhost:7000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

config:
  #RabbitMQ message
  amq:
    hostname: localhost
    port: 5672
    username: guest
    password: guest

  atualizarFrete:
    exchange: atualizarFrete.exchange
    sendDLQQueue: atualizarFrete.sendDLQQueue
    sendQueue: atualizarFrete.sendQueue

  faturamento:
    exchange: registrarFaturamento.exchange
    sendDLQQueue: registrarFaturamento.sendDLQQueue
    sendQueue: registrarFaturamento.sendQueue

  calcularFrete:
    exchange: calcularFrete.exchange
    sendDLQQueue: calcularFrete.sendDLQQueue
    sendQueue: calcularFrete.sendQueue

  expedicao:
    exchange: enviarExpedicao.exchange
    sendDLQQueue: enviarExpedicao.sendDLQQueue
    sendQueue: enviarExpedicao.sendQueue


---
spring:
  profiles: docker-compose

freteExterno:
  ribbon:
    listOfServers: http://integrador:7000

config:
  #RabbitMQ message
  amq:
    hostname: rabbitmq
    port: 5672
    username: guest
    password: guest


