server:
  port: 8081

config:
  #RabbitMQ message
  amq:
    hostname: localhost
    port: 5672
    username: guest
    password: guest

  atualizarFrete:
    exchange: atualizarFrete.exchange
    sendDLQQueue: atualizarFrete.sendDLQQueue
    sendQueue: atualizarFrete.sendQueue

  logistica:
    exchange: logistica.exchange
    sendDLQQueue: logistica.sendDLQQueue
    sendQueue: logistica.sendQueue

  calcularFrete:
    exchange: calcularFrete.exchange
    sendDLQQueue: calcularFrete.sendDLQQueue
    sendQueue: calcularFrete.sendQueue


