
server:
  port: 8888

spring:
  application:
    name: configServer

  cloud:
    config:
      server:
        git:
          uri: https://example.com/my/repo
          timeout: 4

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
