server:
  port: 8888

spring:
  application:
    name: configServer

  cloud:
    config:
      server:
        git:
#          uri: https://github.com/adrianolego/Config.git
          uri: https://github.com/adrianolego/Config.git

#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#
#logging:
#  level:
#    com:
#      netflix:
#        eureka: OFF
#        discovery: OFF
