##Servidor Web
server:
  port: 8081

  keycloak:
    auth-server-url: http://localhost:8080/auth
    resource: coleta
    realm: master
    public-client: true

    security-constraints[0]:
      authRoles: user
      securityColletions[0]:
        pattners[0]: /pedido/*

config:
  #RabbitMQ message
  amq:
    hostname: localhost
    port: 5672
    username: guest
    password: guest

  calcularFrete:
    exchange: calcularFrete.exchange
    sendDLQQueue: calcularFrete.sendDLQQueue
    sendQueue: calcularFrete.sendQueue

  registrarEncomenda:
    exchange: registrarEncomenda.exchange
    sendDLQQueue: registrarEncomenda.sendDLQQueue
    sendQueue: registrarEncomenda.sendQueue

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false


---
spring:
  profiles: docker-compose
config:
  amq:
    hostname: rabbitmq
    port: 5672
    username: guest
    password: guest

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    preferIpAddress: true


#  keycloak:
#    auth-server-url: http://localhost:9090/auth/
#    resource: controledecoleta
#    realm: Keycloak
#    public-client: true


