server:
  port: 8086

integrador:
  ribbon:
    listOfServers: http://localhost:7000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

config:
  #RabbitMQ message
  amq:
    hostname: localhost
    port: 5672
    username: guest
    password: guest

  enviarExpedicao:
    exchange: enviarExpedicao.exchange
    sendDLQQueue: enviarExpedicao.sendDLQQueue
    sendQueue: enviarExpedicao.sendQueue

  atualizarExpedicao:
    exchange: atualizarExpedicao.exchange
    sendDLQQueue: atualizarExpedicao.sendDLQQueue
    sendQueue: atualizarExpedicao.sendQueue


---
spring:
  profiles: docker-compose

config:
  #RabbitMQ message
  amq:
    hostname: rabbitmq
    port: 5672
    username: guest
    password: guest

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    preferIpAddress: true

