server:
  port: 8083

integrador:
  ribbon:
    listOfServers: http://localhost:7000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

config:
  #RabbitMQ message
  amq:
    hostname: localhost
    port: 5672
    username: guest
    password: guest


  registrarFaturamento:
    exchange: registrarFaturamento.exchange
    sendDLQQueue: registrarFaturamento.sendDLQQueue
    sendQueue: registrarFaturamento.sendQueue

  atualizarFaturamento:
    exchange: atualizarFaturamento.exchange
    sendDLQQueue: atualizarFaturamento.sendDLQQueue
    sendQueue: atualizarFaturamento.sendQueue

---
spring:
  profiles: docker-compose

config:
  #RabbitMQ message
  amq:
    hostname: rabbitmq
    port: 5672
    username: guest
    password: guest


