server:
  port: 8082

# freteExterno:
#   ribbon:
#     listOfServers: http://localhost:7000

integrador:
  ribbon:
    listOfServers: http://localhost:7000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

config:
  #RabbitMQ message
  amq:
    hostname: localhost
    port: 5672
    username: guest
    password: guest

  atualizarFrete:
    exchange: atualizarFrete.exchange
    sendDLQQueue: atualizarFrete.sendDLQQueue
    sendQueue: atualizarFrete.sendQueue

  registrarFaturamento:
    exchange: registrarFaturamento.exchange
    sendDLQQueue: registrarFaturamento.sendDLQQueue
    sendQueue: registrarFaturamento.sendQueue

  calcularFrete:
    exchange: calcularFrete.exchange
    sendDLQQueue: calcularFrete.sendDLQQueue
    sendQueue: calcularFrete.sendQueue

  enviarExpedicao:
    exchange: enviarExpedicao.exchange
    sendDLQQueue: enviarExpedicao.sendDLQQueue
    sendQueue: enviarExpedicao.sendQueue

  agendarVeiculo:
    exchange: agendarVeiculo.exchange
    sendDLQQueue: agendarVeiculo.sendDLQQueue
    sendQueue: agendarVeiculo.sendQueue

spring: 
  main: 
    allow-bean-definition-overriding: true


---
spring:
  profiles: docker-compose
config:
  #RabbitMQ message
  amq:
    hostname: rabbitmq
    port: 5672
    username: guest
    password: guest

# freteExterno:
#   ribbon:
#     listOfServers: http://integrador:7000

integrador:
  ribbon:
    listOfServers: http://integrador:7000


