server:
  port: 8084

integrador:
  ribbon:
    listOfServers: http://localhost:7000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

config:
  #RabbitMQ message
  amq:
    hostname: localhost
    port: 5672
    username: guest
    password: guest

  enviarLogistica:
    exchange: enviarLogistica.exchange
    sendDLQQueue: enviarLogistica.sendDLQQueue
    sendQueue: enviarLogistica.sendQueue

  atualizarVeiculo:
    exchange: atualizarVeiculo.exchange
    sendDLQQueue: atualizarVeiculo.sendDLQQueue
    sendQueue: atualizarVeiculo.sendQueue

  agendarVeiculo:
    exchange: agendarVeiculo.exchange
    sendDLQQueue: agendarVeiculo.sendDLQQueue
    sendQueue: agendarVeiculo.sendQueue

---
spring:
  profiles: docker-compose

config:
  #RabbitMQ message
  amq:
    hostname: rabbitmq
    port: 5672
    username: guest
    password: guest

  eureka:
    client:
      serviceUrl:
        defaultZone: http://eurekaserver:8761/eureka
    instance:
      preferIpAddress: true


