#Servidor Web
server:
  port: 8087

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false

config:
  #Mongo
  mongodb:
    hostname: localhost
    port: 27017
    database: controledelogistica

  #RabbitMQ message
  amq:
    hostname: localhost
    port: 5672
    username: guest
    password: guest

  registrarEncomenda:
    exchange: registrarEncomenda.exchange
    sendDLQQueue: registrarEncomenda.sendDLQQueue
    sendQueue: registrarEncomenda.sendQueue

  atualizarFrete:
    exchange: atualizarFrete.exchange
    sendDLQQueue: atualizarFrete.sendDLQQueue
    sendQueue: atualizarFrete.sendQueue

  atualizarVeiculo:
    exchange: atualizarVeiculo.exchange
    sendDLQQueue: atualizarVeiculo.sendDLQQueue
    sendQueue: atualizarVeiculo.sendQueue

  atualizarLogistica:
    exchange: atualizarLogistica.exchange
    sendDLQQueue: atualizarLogistica.sendDLQQueue
    sendQueue: atualizarLogistica.sendQueue

  atualizarExpedicao:
    exchange: atualizarExpedicao.exchange
    sendDLQQueue: atualizarExpedicao.sendDLQQueue
    sendQueue: atualizarExpedicao.sendQueue

  #Redis
  redis:
    hostname: localhost
    port: 6379
    enabled: false

---
spring:
  profiles: docker-compose

config:
  #Mongo
  mongodb:
    hostname: mongodb
    port: 27017
    database: controledelogistica

  #RabbitMQ message
  amq:
    hostname: rabbitmq
    port: 5672
    username: guest
    password: guest

  #Redis
  redis:
    hostname: localhost
    port: 6379
    enabled: false

  #Eureka
  eureka:
    client:
      serviceUrl:
        defaultZone: http://eurekaserver:8761/eureka
    instance:
      preferIpAddress: true








