##Servidor Web
server:
  port: 8081

keycloak:
  realm: logistica
  bearer-only: true
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: logistica
  verify-token-audience: true
  use-resource-role-mappings: true
  confidential-port: 0

config:
  #RabbitMQ message
  amq:
    hostname: localhost
    port: 5672
    username: guest
    password: guest

  calcularFrete:
    exchange: calcularFrete.exchange
    sendDLQQueue: calcularFrete.sendDLQQueue
    sendQueue: calcularFrete.sendQueue

  registrarEncomenda:
    exchange: registrarEncomenda.exchange
    sendDLQQueue: registrarEncomenda.sendDLQQueue
    sendQueue: registrarEncomenda.sendQueue

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false


---
spring:
  profiles: docker-compose
config:
  amq:
    hostname: rabbitmq
    port: 5672
    username: guest
    password: guest

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    preferIpAddress: true


  keycloak:
    auth-server-url: http://keycloak:9090/auth/
    resource: controledecoleta
    realm: Keycloak
    public-client: true


