config:
#RabbitMQ message
  amq:
    hostname: localhost
    port: 5672
    username: guest
    password: guest

  calcularFrete:
    exchange: calcularFrete.exchange
    sendDLQQueue: calcularFrete.sendDLQQueue
    sendQueue: calcularFrete.sendQueue

  encomenda:
    exchange: encomenda.exchange
    sendDLQQueue: encomenda.sendDLQQueue
    sendQueue: encomenda.sendQueue

